# Generated by Django 5.2.2 on 2025-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_company_remove_job_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
